### ISSUE TITLE
Regular expression input is not escaped when pressing backspace

### ISSUE THREAD

**Issue by speich** [digitalfortress-tech/typeahead-standalone#22]
When the selected item from the suggestions contains a reserved character, e.g. `[` and backspace is pressed, the following error is thrown in updateHint(): `unterminated character class`

select item from list
![image](https://user-images.githubusercontent.com/649653/172791986-59286d01-f184-4793-bf2e-d955b7e9e097.png)
press backspace

![image](https://user-images.githubusercontent.com/649653/172792243-22aaaa3b-0889-4598-a107-3e5b0a460ec1.png)

**Comment by niketpathak** [comment]
Hello @speich , thank you for reporting this bug. It has been corrected in `v4.3.0`  ([Ref](https://github.com/digitalfortress-tech/typeahead-standalone/releases/tag/release_v4.3.0))
