### ISSUE TITLE
Moving instead of cloning changes order of elements in parent element

### ISSUE THREAD

**Issue by speich** [digitalfortress-tech/typeahead-standalone#27]
### What happened?

Fixing issue#26 introduced a new bug. Appending the input to the parent element, moves it to the end of the DOM tree of the parent element. Probably `insertBefore()` should be used instead of `appendChild()` in https://github.com/digitalfortress-tech/typeahead-standalone/blob/master/src/typeahead-standalone.ts#L100

### Affected version

v4.8.0

### Reproduction URL

https://jsfiddle.net/57kbLsec/

### How to reproduce?

note changed order of siblings in container element.

**Comment by niketpathak** [comment]
Thank you for pointing this out. Fixed in [v4.9.0](https://github.com/digitalfortress-tech/typeahead-standalone/releases/tag/v4.9.0)
