### ISSUE TITLE
Arrow key does not always select an item from the list.

### ISSUE THREAD

**Issue by speich** [digitalfortress-tech/typeahead-standalone#28]
### What happened?

When using the arrow key to select an item from the suggestions, sometimes nothing gets selected event though there are suggestions in the list. This happens only after the initial requests (caching?) for the pressed keys.

### Affected version

v4.9.0

### Reproduction URL

https://codepen.io/niketpathak/pen/ZExLeEw

### How to reproduce?

1. go to the link
2. press keys: ab
3. press key: arrow down --> first item in list gets selected
4. press key: c
5. press key: arrow down  --> first item in list gets selected
6. press 3 x backspace
7. press keys: ab
8. press key: arrow down --> first item in list gets selected
9. press key: c
10. press key: arrow down   --> nothing gets selected from the list anymore, even though there are items in it. Also note, that the character c gets deleted. Pressing key up will select first item in the list

**Comment by niketpathak** [comment]
yes, indeed. Working on a fix asap. As usual, thank you for reporting it.
