### ISSUE TITLE
With hint: false, a tt-hint input box is still generated

### ISSUE THREAD

**Issue by haydentech** [digitalfortress-tech/typeahead-standalone#38]
### What happened?

Expected behavior:
Setting hint:false in the typeahead options will not produce a tt-hint input element in the output html

Actual behavior:
A tt-hint input is created anyway, just not used for hinting

I don't want hinting, and the unused, mis-sized tt-hint input box is making a mess of my search box ui.  If I go into devtools and manually delete the tt-hint input element, everything looks and works correctly.

### Affected version

Latest

### Reproduction URL

https://jsfiddle.net/j7xL59m8/

### How to reproduce?

1. Set hint: false in the typeahead options
2. Notice that the tt-hint input box is still generated when the page is rendered

### Browsers

Firefox, Chrome

**Comment by niketpathak** [comment]
Hello @haydentech ,

Thank you for reporting this. There are 2 solutions to this issue. 

1. Hide the hint element via css
```css
.tt-hint {
    display: none;
}
```

2. [**Recommended**] Update to the latest version [v4.14.0](https://github.com/digitalfortress-tech/typeahead-standalone/releases/tag/v4.14.0) which fixes this bug and removes the hint element from the DOM when it is disabled. 

Note that after disabling the hint, depending on your websites color theme, you may have to set a background color for your input element to ensure consistency. For example -

.tt-input { 
    background: #fff; 
}

Hope that helps!

**Comment by haydentech** [comment]
Thanks so much... impressive turn-around time!  That fixed things for me.  I'm very impressed with the module as a whole.

**Comment by niketpathak** [comment]
Thanks to you too for taking the time to report it!
