### ISSUE TITLE
Generated HTML is not valid

### ISSUE THREAD

**Issue by drgrice1** [digitalfortress-tech/typeahead-standalone#53]
### What happened?

The HTML generated by the javascript is not valid.  A `span` tag is created to wrap the original input element, a hint input is added, and then a `div` tag is also added into that `span`.  It is not valid HTML to have a `div` tag inside a `span`.

Additionally, the `readonly` attribute is added to the hint input with the value of "true".  The `readonly` attribute is a boolean value, but the string value of "true" is not a boolean.  Boolean attributes should be set with no value at all.

On a side note, I have noticed that on pages that use Bootstrap the hidden input initially appears offset from the original input.  A quick fix is to add the style "display: block" to the wrapping `span` (which would be needed if this were a `div` anyway).

One final note.  The attributes of the original input are copied to the added hint input.  The `id` attribute is not copied which is good, but if the original input has an `aria-label` that is copied.  That attribute should not be copied.

### Affected version

v4.18.0

### Reproduction URL

https://codepen.io/niketpathak/pen/eYVdGNY

### How to reproduce?

1.  Use this javascript library in any browser.
2.  Add bootstrap to the page.
3. Put an aria-label on the original input.

### Browsers

Firefox, Chrome

### Additional context

The codepen is just your default codepen.  I don't see the need to create a custom codepen for this.  I think the issues are pretty clear as is.

**Comment by niketpathak** [comment]
Hello @drgrice1 , thank you your valuable inputs. You are right concerning the `div` within the `span` as well as your comments regarding the html attributes used. This will be corrected in the next release. Thanks!

**Comment by niketpathak** [comment]
Fixed in [v4.19.0](https://www.npmjs.com/package/typeahead-standalone/v/4.19.0)

**Comment by drgrice1** [comment]
Thanks for looking into this.
