### ISSUE TITLE
Native Input Event Not Being Triggered

### ISSUE THREAD

**Issue by HansMusterWhatElse** [digitalfortress-tech/typeahead-standalone#60]
### What happened?

Hi there 👋,

As of today the propagation of the [**native input event**](https://github.com/digitalfortress-tech/typeahead-standalone/blob/70668092359607fee5cbebdde1e59bf94a2b8bc6/src/typeahead-standalone.ts#LL345C1-L346C1) is currently commented as a result of a [**bug**](https://github.com/digitalfortress-tech/typeahead-standalone/issues/54).

This way we are not able to react to any changes when the user selects a value from the `suggestion-list`. Is there already a solution how this will be handled in the future?

### Affected version

Latest

### Reproduction URL

https://github.com/digitalfortress-tech/typeahead-standalone/blob/70668092359607fee5cbebdde1e59bf94a2b8bc6/src/typeahead-standalone.ts#LL345C1-L346C1

### How to reproduce?

1. Attach an `input` event handler to the input field
2. Type a prefix of a value and select a value from the suggestion list

### Browsers

Chrome

**Comment by HansMusterWhatElse** [comment]
Hi @niketpathak ,

Thanks for the fast reply - this would work out as a workaround. I still think its not wise to break the native capabilities when setting the `value` without dispatching the corresponding native input event. Is there a specific reason why you opted out of this?

With this solution the consumer of the library is now responsible to ensure parity to the native behavior. At the moment this breaks many of the form libraries.

Have a great day! 👍

**Comment by niketpathak** [comment]
Hello @HansMusterWhatElse , after pondering about your last comment. I agree that to be at parity with respect with 3rd party libraries, an input event must be emitted: Thank you for your feedback. This has been implemented in [v4.21.0](https://www.npmjs.com/package/typeahead-standalone/v/4.21.0).

Updated documentation can be found [here](https://typeahead.digitalfortress.tech/#references?id=faq).

**Comment by HansMusterWhatElse** [comment]
> Hello @HansMusterWhatElse , after pondering about your last comment. I agree that to be at parity with respect with 3rd party libraries, an input event must be emitted: Thank you for your feedback. This has been implemented in [v4.21.0](https://www.npmjs.com/package/typeahead-standalone/v/4.21.0).
> 
> Updated documentation can be found [here](https://typeahead.digitalfortress.tech/#references?id=faq).

That's great news! Thank you so much! 🙂👍
