### ISSUE TITLE
cannot keydown through defaultItems in empty resultSet

### ISSUE THREAD

**Issue by markengelstad** [digitalfortress-tech/typeahead-standalone#71]
### What happened?

Upon focus into the typeahead, before typing input, templates.empty displays a resultSet of defaultItems.  The suggestions from these defaultItems can be clicked upon but you cannot arrow-down through the listed suggestions.  

Instead, upon arrow-down, the suggestions disappear. 

this behavior is displayed in the [playground 1: colors option](https://typeahead.digitalfortress.tech/#playground)

### Affected version

Latest

### Reproduction URL

https://typeahead.digitalfortress.tech/#playground

### How to reproduce?

1. focus on typeahead
2. key down arrow

### Browsers

Chrome

**Comment by niketpathak** [comment]
Hello @markengelstad , Thank you for reporting this bug. It has been fixed in [v4.24.0](https://www.npmjs.com/package/typeahead-standalone)
