### ISSUE TITLE
typeahead-standalone wont scroll result content using bootstrap 5 offcanvas component

### ISSUE THREAD

**Issue by AlonsoK28** [digitalfortress-tech/typeahead-standalone#79]
### What happened?

using typeahead-standalone within an [bootstrap 5](https://getbootstrap.com/docs/5.3/components/offcanvas/#how-it-works) offcanvas component wont scroll content

### Affected version

Latest

### Reproduction URL

https://codepen.io/C-Alonso-C-Ortega/pen/RwOzdPK

### How to reproduce?

1. create a basic example using bs5 offcanvas component together typeahead-standalone
2. open offcanvas
3. write a search term
4. get results an see that scroll doesnt happen
note. reproduce issue using this example https://codepen.io/C-Alonso-C-Ortega/pen/RwOzdPK

### Browsers

Chrome

**Comment by niketpathak** [comment]
Hello @AlonsoK28 , this is not really a bug with typeahead. Its more related to your code/css. Here's a [codepen](https://codepen.io/niketpathak/pen/XWQvrOO) that works as expected.

**Comment by AlonsoK28** [comment]
Thank you very much for the help.

I think it would be helpful to include this example since boostrap is one of the most popular frontend frameworks.

Eventually someone will need to know how to do this.
