### ISSUE TITLE
Use enter when showing empty list

### ISSUE THREAD

**Issue by verschoof** [digitalfortress-tech/typeahead-standalone#86]
### What happened?

I want to be able to use enter to select the item in the "empty list".

It also happens in the demo:
https://typeahead.digitalfortress.tech/#playground?id=colors-example

When it does work:
1 . click on the input
2. Type the letter `b`
3. Press 2 times arrow down
4. Hit enter

Now you have selected the select

### Affected version

Latest

### Reproduction URL

https://codepen.io/niketpathak/pen/vYRKdNq

### How to reproduce?

1 Click on the input (you should see now the list of popular colors)
2 Press 2 times arrow down (You should have your selection on `Green`)
3 Press enter to select `Green`

### Browsers

Brave

### Relevant log output

```Shell
No errors in the console
```

**Comment by verschoof** [comment]
@niketpathak I don't want to pressure, I don't know how much you work on this project but in what time I can expect a fix & release?

Unfortunately my typescript kills are not enough to help with a pull request 😞

**Comment by niketpathak** [comment]
@verschoof , For bugs, I'm usually quite quick to resolve them. So you can expect a fix by tomorrow at the latest.

**Comment by niketpathak** [comment]
@verschoof , this isse was fixed in `v5.3.1`. Thank you for reporting it.
